DROP DATABASE IF EXISTS `fifteen`;
CREATE DATABASE `fifteen` DEFAULT CHARACTER SET utf8mb4;

USE `fifteen`;

CREATE TABLE `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` TEXT,
  `auth_uid` VARCHAR(100) UNIQUE,
  `experience` BIGINT NOT NULL DEFAULT 0,
  `pinks` BIGINT NOT NULL DEFAULT 0,
  `tier_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`tier_id`) REFERENCES tiers(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tiers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` TEXT,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `friendships` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id1` BIGINT NOT NULL,
  `user_id2` BIGINT NOT NULL,
  FOREIGN KEY (`user_id1`) REFERENCES users(`id`)
  FOREIGN KEY (`user_id2`) REFERENCES users(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
